project
Science-B/ScienceB pull request #1
Opened 2021-06-01 19:41 UTC by Science-B

2021-06-01 20:15 UTC, bakalux requested changes

2021-06-01 20:15 UTC, bakalux commented on index.css
> +  max-width: 1920px;
не ставь селекторы на тэги, только на классы. Тут добавь просто класс `.header`

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.SEARCH {background: #C62306;
названия классов всегда в `camelCase`

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.SEARCH {background: #C62306;
Поставь расширение Prettier, чтобы он при сохранении форматировал отступы

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.SEARCH button {
тоже на кнопку класс вместо тэга

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.button_top {
есть правила наименования переменных `camelCase`, `snake_case`, `kebab-case`, `PascalCase`. На фронте почти везде наименования идут в `camelCase`.

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.button_top a {
camelCase

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.btn_help_top {
тут тоже

2021-06-01 20:15 UTC, bakalux commented on index.css
> +  align-items: center;
отступы

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.button_shop a {
класс вместо тэга

2021-06-01 20:15 UTC, bakalux commented on index.css
> +nav {
и тут

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.kabinet {
классы на английском должны быть

2021-06-01 20:15 UTC, bakalux commented on index.css
> +width: 1519px;
не должно быть фиксированной ширины, навигация должна зависеть от контента. Если у тебя добавится новый пункт навигации или поменяется где-то название, то у тебя всё поедет из-за фиксированной ширины

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.nav-menu li {
тэги

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.nav-menu li a {
тэги

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.nav-menu li a p{
тэги

2021-06-01 20:15 UTC, bakalux commented on index.css
> +  .button_call a {
тэг

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.slider a {
Ы

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.slider HR {
шок шо за тэг

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.h1_2 {
эти буквы цифры ни о чем не говорят, вообще непонятно что за классы и зачем нужны, нет семантики

2021-06-01 20:15 UTC, bakalux commented on index.css
> +  width: 295px;
фиксированная высота ширина, тоже если что-то будешь менять в плане контента то всё поедет

2021-06-01 20:15 UTC, bakalux commented on index.css
> +margin-top: 30px;;
лишняя `;`

2021-06-01 20:15 UTC, bakalux commented on index.css
> +  .shariki {
balls?

2021-06-01 20:15 UTC, bakalux commented on index.css
> +.bst_1 {
че за класс непонятно буквы цифры

2021-06-01 20:15 UTC, bakalux commented on index.css
> +    margin-top: 91.85px;
не ставь неполные пиксели, округляй до целых всегда

2021-06-01 20:15 UTC, bakalux commented on index.html
> +                                <ul class="kek"><li><img src="images\block_5.svg" alt="#"></li>
форматирование файла от Prettier нужно, всё поехало

2021-06-02 16:04 UTC, Science-B commented on index.css
> +.SEARCH {background: #C62306;
Сделал

2021-06-02 16:18 UTC, Science-B commented on index.css
> +.SEARCH {background: #C62306;
Сделал

2021-06-02 16:18 UTC, Science-B commented on index.css
> +.bst_1 {
Та хз, тогда удобно было

2021-06-02 16:19 UTC, Science-B commented on index.css
> +    margin-top: 91.85px;
Сделал

2021-06-02 16:32 UTC, Science-B commented on images/1klass.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Понял, не буду скачивать заного.

2021-06-02 16:32 UTC, Science-B commented on images/1klass.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
не туда

2021-06-02 16:32 UTC, Science-B commented on images/block 8.svg
> +<svg width="77" height="77" viewBox="0 0 77 77" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Понял, не буду скачивать заново.

2021-06-02 16:33 UTC, Science-B commented on index.html
> +                                <ul class="kek"><li><img src="images\block_5.svg" alt="#"></li>
Сделал

2021-06-02 16:33 UTC, Science-B commented on index.css
> +margin-top: 30px;;
Сделал

2021-06-02 16:42 UTC, Science-B commented on images/1klass.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Я понял про это, видики посмотрел, но лень все картинки пропускать через. Потому учту.

2021-06-02 16:43 UTC, merged